unboxing96/CurrentMood

- main/templates/main/test.html
- main/templates/main/test2.html
- main/urls.py
- main/views.py
재생 목록에서 이전 곡 재생, 다음 곡 재생, 자동 재생 가능하게 함.
> feat : 재생 목록 기능 추가 [김선교]

- accounts/templates/accounts/my_sharedmusiclist.html
- accounts/urls.py
- accounts/views.py
fix : 내 정보 페이지 서버에러 수정 [이동현]
- 내 정보 화면으로가면 서버에러 뜨던것 코드 수정
- 내가 쓴 글 목록을 불러오는 템플릿이 삭제 되어 못찾아서 발생되는 오류
- 다시 생성해서 오류 해결
> fix : 내 정보 페이지 서버에러 수정 [이동현]

- main/templates/main/base.html
session middleware 사용하여 기능 구현함.
> feat : 페이지 이동 시에도 끊김없이 재생할 수 있는 기능 추가 [김선교]

- .ebextensions/django.config
- .github/workflows/deploy.yml
- articles/forms.py
- config/settings.py
- requirements.txt
> feat : 배포 기능 [이동현]

- config/settings.py
> fix : 배포 오류 수정중 [이동현]

- accounts/templates/accounts/mypage.html
- accounts/templates/accounts/profile_music.html
- articles/templates/articles/create.html
- articles/templates/articles/detail.html
- main/templates/main/base.html
게시글에 등록된 음악을 클릭하면 재생 목록에 넣는 기능 구현함.
> feat : 게시글 노래 재생 기능 추가 [김선교]

- articles/templates/articles/index.html
- articles/views.py
- main/templates/main/base.html
가장 인기 있는 곡 표시 & 다음으로 인기 있는 곡들 캐러셀 구현함.
> feat : index 페이지 대폭 수정 [김선교]

- config/settings.py
> fix : 배포 오류 수정 [이동현]

- config/settings.py
> fix : 배포 오류 DB 수정중 [이동현]

- .github/workflows/deploy.yml
> fix : 배포 두번뜨는 것 코드 수정 [이동현]

- config/settings.py
refact : 배포시 DB 반영 안되게 수정 [이동현]
> refact : 배포시 DB 반영 안되게 수정 [이동현]

- config/settings.py
> style : admin 계정 생성 [이동현]

- config/settings.py
> style : 어드민 계정 생성 [이동현]

- articles/templates/articles/create.html
- config/settings.py
> fix : 인덱스페이지 글쓰기 위한 코드 [이동현]

- config/settings.py
deploy : DB 배포 안되게 세팅즈 코드 수정 [이동현]
> deploy : DB 배포 안되게 세팅즈 코드 수정 [이동현]

- accounts/templates/accounts/mypage.html
- main/templates/main/base.html
style : 내 정보 페이지에서 뒤로가기 삭제 [이동현]
> style : 내 정보 페이지에서 뒤로가기 삭제 [이동현]

- config/settings.py
> fix : 도메인 400 에러 수정 [이동현]

- articles/templates/articles/detail.html
- articles/views.py
feat : 게시글 상세페이지 좋아요 비동기 기능 [이동현]
> feat : 게시글 상세페이지 좋아요 비동기 기능 [이동현]

- config/settings.py
deploy : migrate 적용을 위한 커밋 [이동현]
> deploy : migrate 적용을 위한 커밋 [이동현]

- accounts/views.py
- articles/templates/articles/private.html
feat : 메인페이지 댓글창에 좋아요 비동기 추가 [이동현]
> feat : 메인페이지 댓글창에 좋아요 비동기 추가 [이동현]

- accounts/templates/accounts/mypage.html
- accounts/urls.py
- articles/templates/articles/private.html
- config/settings.py
- config/urls.py
fix : 내 정보에서 이미지 안보이는 버그 수정 [이동현]
> fix : 내 정보에서 이미지 안보이는 버그 수정 [이동현]

- config/settings.py
> refact : DEBUG 값 수정 [이동현]

- accounts/templates/accounts/mypage.html
> fix : 내 정보 페이지화면 오류 수정 [이동현]

- articles/templates/articles/song_detail.html
- articles/views.py
test : song_detail 페이지에 좋아요 비동기x 추가 [이동현]
> test : song_detail 페이지에 좋아요 비동기x 추가 [이동현]

- articles/templates/articles/song_detail.html
test : song_detail 페이지 링크 뺀 하트만 넣음 [이동현]
> test : song_detail 페이지 링크 뺀 하트만 넣음 [이동현]

- articles/templates/articles/song_detail.html
test : song_detail 페이지 링크 다 뺀 하트 이모티콘만 넣음 [이동현]
> test : song_detail 페이지 링크 다 뺀 하트 이모티콘만 넣음 [이동현]

- articles/templates/articles/song_detail.html
test : song_detail 페이지 하트 갯수 코드 빼고 하트 좋아요 기능 넣음 [이동현]
> test : song_detail 페이지 하트 갯수 코드 빼고 하트 좋아요 기능 넣음 [이동현]

- articles/templates/articles/song_detail.html
- articles/views.py
test : song_detail 페이지 좋아요 비동기 코드 넣음 [이동현]
> test : song_detail 페이지 좋아요 비동기 코드 넣음 [이동현]

- articles/templates/articles/song_detail.html
test : song_detail 페이지 console.log 코드 추가 [이동현]
> test : song_detail 페이지 console.log 코드 추가 [이동현]

- articles/templates/articles/song_detail.html
test : song_detail 페이지 테스트중 [이동현]
> test : song_detail 페이지 테스트중 [이동현]

- config/settings.py
> deploy : 서버에 로컬 DB 반영 [이동현]

- articles/templates/articles/song_detail.html
- config/settings.py
fix : song_detail 페이지 서버 오류 수정중 [이동현]
> fix : song_detail 페이지 서버 오류 수정중 [이동현]

- accounts/templates/accounts/mypage.html
fix : 내 정보 페이지 서버 오류 수정중 [이동현]
> fix : 내 정보 페이지 서버 오류 수정중 [이동현]

- accounts/templates/accounts/profile_music.html
- articles/templates/articles/create.html
- articles/templates/articles/create_test.html
- articles/templates/articles/update.html
- articles/views.py
> style : api 수정 [이동현]

- config/settings.py
> deploy : 로컬 DB 반영 [이동현]

- config/settings.py
> deploy : DB 관련 코드 원복 [이동현]

- accounts/views.py
style : 주소/accounts/ 에는 admin 계정만 접근 가능 [이동현]
> style : 주소/accounts/ 에는 admin 계정만 접근 가능 [이동현]
